import './globals.css';

import { NextIntlClientProvider } from 'next-intl';

import { getUserLocale } from '@/actions/locale-action';

import { Toaster } from '@/components/ui/sonner';

import { ThemeProvider } from '@/providers/theme-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({ children }) {
  const locale = await getUserLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={
          locale === 'ko'
            ? 'font-noto-kr'
            : locale === 'zh-TW'
              ? 'font-noto-tc'
              : locale === 'th'
                ? 'font-noto-thai'
                : 'font-noto'
        }
      >
        <NextIntlClientProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster richColors />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
